# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=4096']

-   repo: https://github.com/timothycrosley/isort
    rev: 5.9.2
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    -   id: black
