name: vqr
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # Dev deps
  - black
  - ipython
  - isort
  - jupyter
  - jupyterlab
  - jupyterlab-spellchecker
  - matplotlib
  - nodejs
  - pre-commit
  - pytest
  - pytest-benchmark
  - pytest-cov
  - pytest-repeat
  - pytest-xdist
  # Deps
  - cvxpy
  - numpy
  - pandas
  - pip
  - pot
  - python=3.9.*
  - pytorch
  - requests
  - scikit-learn
  - scipy
  - tqdm
  - pip:
    - -e . # install this package
