name: vqr
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Development deps
  - black
  - click
  - cmake # needed to compile cvxpy when installed via pip
  - ipython
  - isort
  - jupyter
  - jupyterlab
  - jupyterlab-spellchecker
  - llvm-openmp
  - matplotlib
  - nodejs
  - pandas
  - pip
  - pre-commit
  - pytest
  - pytest-benchmark
  - pytest-cov
  - pytest-repeat
  - pytest-rerunfailures
  - pytest-xdist
  - python=3.9.*
  - requests

  # VQR lib
  # control pytorch version (won't be installed again by pip install -e .)
  - pytorch=1.11.*
  - cudatoolkit=11.3 # comment out on osx-arm64
  - cudatoolkit-dev=11.3 # comment out on osx-arm64
  - pip:
    - pykeops
    - geomloss
    # install vqp as a lib with pip (its deps are specified in setup.cfg)
    # Note: For KeOps to work, after installing this env run:
    # conda env config vars set CPATH="${CONDA_PREFIX}/include:${CPATH}"
    # conda env config vars set LD_LIBRARY_PATH="$CONDA_PREFIX/lib64:$LD_LIBRARY_PATH"
    - -e .

platforms:
  - osx-64
  - osx-arm64
  - linux-64
