version: 1
formatters:
  simple:
    format: '[%(asctime)s %(name)20s] %(levelname)7s >> %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  vqr:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: WARNING
  handlers: [console]
