# This is a basic workflow to help you get started with Actions

name: github-ci

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup-conda
        # You may pin to the exact commit or the version.
        # uses: s-weigand/setup-conda@bf65a211e008297225b737b153801ac1231e9758
        uses: s-weigand/setup-conda@v1.0.5
        with:
          # Whether to activate the conda base env (Default: 'true')
          activate-conda: false # optional, default is true
          # If conda should be updated before running other commands (Default: 'false')
          update-conda: false # optional, default is false
          # Python version which should be installed with conda (default: 'Default')
          python-version: 3.8 # optional, default is default
          # Additional channels like 'conda-forge' which can be used to install packages
          conda-channels: conda-forge # optional, default is

      - name: Install deps
        run: conda env update -f environment.yml -n vqr

      - name: Run tests
        run: |
          source activate vqr
          pytest
